name: Test

on:
  push:
    branches: # Array of patterns that match refs/heads
      - main # Push events on main branch
  pull_request: # Specify a second event with pattern matching
env:
  CI: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 21.x, 22.x, 24.x]
    steps:
      # https://github.com/actions/checkout/releases/tag/v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Use Node.js ${{ matrix.node-version }}
        # https://github.com/actions/setup-node/releases/tag/v6.3.0
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore Dependencies
        # https://github.com/actions/cache/releases/tag/v5.0.4
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{matrix.node-version}}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{matrix.node-version}}-
      - run: npm ci
      - run: npm run build
      - run: npm run format:check
      - run: npm run lint
      - run: npm run jest
      - run: npm run examples
      - run: npm run benchmarks
      - name: Coveralls GitHub Action
        # Per Actions best practices, SHA is the safest for third party actions
        # https://github.com/coverallsapp/github-action/releases/tag/v2.3.7
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-unit-${{ matrix.node-version }}
          parallel: true

  finish:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        # Per Actions best practices, SHA is the safest for third party actions
        # https://github.com/coverallsapp/github-action/releases/tag/v2.3.7
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
